name: Build 67 Snake Game APK
on:
  push
  workflow_dispatch:
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: dawidd6/action-flutter@v2
        with:
          flutter-version: '3.10.5'
          java-version: '17'
      - name: Install dependencies
        run: |
         flutter pub get
      - name: Build APK
        run: |
         flutter build apk --release
          mv app-release.apk 67_snake_game.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: six7-android-apk
          path: 67_snake_game.apk
      - name: Set up Git
        run: |
          git config --global user.email "action@example.com"
          git config --global user.name "GitHub Action"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Build APK for Android 15"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub
        run: git push origin main
secrets:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}